### ISSUE TITLE
Perfect-Scrollbar-JS crashes due to undefined elements

### ISSUE THREAD

**Issue by yvan-burrie** [creativetimofficial/ct-now-ui-dashboard-pro-laravel#6] opened 2021-03-14 16:56 UTC
I am very happy with this UI, so I spent 2 hours troubleshooting this issue, and I have found the solution. You need to modify `now-ui-dashboard.js` on line 53 with the following:

```js
let isWindows = navigator.platform.indexOf('Win') > -1;
if (isWindows) {
  if ($('.sidebar-wrapper').length) {
    new PerfectScrollbar('.sidebar-wrapper');
  }
  if ($('.main-panel').length) {
    new PerfectScrollbar('.main-panel');
  }
  $('html').addClass('perfect-scrollbar-on');
} else {
  $('html').addClass('perfect-scrollbar-off');
}
```

The welcome, login, and register pages do not have `.sidebar-wrapper` nor `.main-panel`, hence, JavaScript crashes when `PerfectScrollbar` is initialised with these missing elements.

**Comment by teamupdivision** [comment] 2021-03-15 13:56
Hi @yvan-burrie,

Thank you very much for using Creative Tim products and for your message. We're really glad you like it! :) 

Regarding the issue, we were not able to reproduce it. Do you think you can help us with some additional details so we can investigate further, please?

All the best,
UPDIVISION Team

**Comment by yvan-burrie** [comment] 2021-03-17 11:26
Thank you for your reply.

You will see the error when inspecting the page. If I browse to your live preview (https://www.creative-tim.com/live/now-ui-dashboard-pro-laravel), then here is what I get:
![Screenshot 2021-03-17 212146](https://user-images.githubusercontent.com/5691628/111460053-3d9cce80-8767-11eb-9ca7-6a404d2a3e1f.png)

As you can see, the `PerfectScrollbar` is not working and the error is shown.

**Comment by teamupdivision** [comment] 2021-03-19 10:27
Hi @yvan-burrie,

Thanks for adding the details. 

The issue was only on Windows so this is why we were not able to reproduce it at the first look. 
We've pushed a fix to this problem and you can download again the product from the downloads section in the Creative Tim.

Please let us know if there is anything else. 

All the best,
UPDIVISON Team

**Comment by teamupdivision** [comment] 2021-03-26 13:59
Hi @yvan-burrie,

Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know. 

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Closed as completed by teamupdivision** 2021-03-26 13:59 UTC
